version: '3.6'
services:
  indexer:
    image: servers/laminar-indexer:latest
    restart: always
    environment:
      DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      WS_URL: wss://testnet-node-1.laminar-chain.laminar.one/ws
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db-data:
